// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
//
// NOTE (placeholder): this file is a COMPILE-TIME STAND-IN for the real
// Wails v3 generated bindings (same path, same shape: $Call.ByID + typed
// $CancellablePromise returns). It is replaced verbatim by
// `wails3 generate bindings` once the Go side (gui/service.go) exists.
// The `__MOCK_BINDINGS__` marker lets frontend/src/lib/api.ts detect the
// stand-in at runtime and fall back to demo data when running the frontend
// standalone (npm run dev / npm run build without the Wails bridge).

import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
} from "@wailsio/runtime";

// Marker: true only while these placeholder bindings are in place.
export const __MOCK_BINDINGS__ = true;

export function GetStatus(): $CancellablePromise<any> {
  return $Call.ByID(0);
}

export function Start(): $CancellablePromise<void> {
  return $Call.ByID(0);
}

export function Stop(): $CancellablePromise<void> {
  return $Call.ByID(0);
}

export function GetRules(): $CancellablePromise<any> {
  return $Call.ByID(0);
}

export function SaveRules(rulesText: string): $CancellablePromise<void> {
  return $Call.ByID(0, rulesText);
}

export function ReloadRules(): $CancellablePromise<void> {
  return $Call.ByID(0);
}

export function UpdateGeo(): $CancellablePromise<any> {
  return $Call.ByID(0);
}

export function SetSystemProxy(enabled: boolean): $CancellablePromise<void> {
  return $Call.ByID(0, enabled);
}

export function GetSystemProxyEnabled(): $CancellablePromise<boolean> {
  return $Call.ByID(0);
}

export function GetConfig(): $CancellablePromise<any> {
  return $Call.ByID(0);
}

export function SaveConfig(configJson: string): $CancellablePromise<void> {
  return $Call.ByID(0, configJson);
}

export function GetLogs(limit: number): $CancellablePromise<any[]> {
  return $Call.ByID(0, limit);
}
